defaults:
  - default

strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  find_unused_parameters: false
  gradient_as_bucket_view: true

accelerator: gpu
devices: -1
num_nodes: 1
sync_batchnorm: true
log_every_n_steps: 20
