defaults:
  - model_checkpoint
  - model_summary
  - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  save_last: link
  auto_insert_metric_name: false

model_summary:
  max_depth: -1
